<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
  </PropertyGroup>

  <ItemGroup>
    <None Include="README.md" CopyToPublishDirectory="PreserveNewest" />
    <None Include="res\**" CopyToPublishDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
